version: '3.6'
services:
  node:
    container_name: meta-node
    restart: always
    networks:
      - services-tier
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $GLS_CONNECTOR_HOST:$GLS_CONNECTOR_PORT:$GLS_CONNECTOR_PORT
      - $GLS_METRICS_HOST:$GLS_METRICS_PORT:$GLS_METRICS_PORT
    env_file:
      - .env

  mongo:
    container_name: meta-mongo
    image: mongo:4
    restart: always
    networks:
      - services-tier
    volumes:
      - mongodb_vol:/data/db
    ports:
      - $GLS_MONGO_EXTERNAL_HOST:$GLS_MONGO_EXTERNAL_PORT:27017

volumes:
  mongodb_vol:

networks:
  services-tier:
